# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    campaignchain.location.mailchimp.newsletter:
        bundle_name: "campaignchain/location-mailchimp"
        module_identifier: "campaignchain-mailchimp-newsletter"

services:
#    campaign_chain_location_mail_chimp.example:
#        class: CampaignChain\Location\MailChimpBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
